defaults:
  - cifar100 # cifar100, chaoyang, micebone or nihao yaml-file in the folder "conf/"
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  - _self_
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

experiment:
  name: PL2D
  tracking_uri: sqlite:///PL2D.db
  logdir: ./logdir
  run_id: null

hparams:
  prob_random_h_flip: 0.5

training:
  gating_lr: 0.01
  expert_lr: 0.01
  num_fixed_point_iterations: 10
  batch_size: 128
  num_epochs: 300
  momentum: 0.9
  weight_decay: 0.0005

data_loading:
  progress_bar: True
  num_workers: 8
  num_threads: 4
  prefetch_size: 2

jax:
  platform: cuda
  mem: 0.9
  disable_jit: False
  dtype: jnp.bfloat16