dataset:
  name: micebone
  root: /sda2/datasets/MiceBone
  num_classes: 3
  missing_rate: 0.7
  train_files:
  - /sda2/datasets/MiceBone/splits_missing/Id_290_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_47_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_533_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_534_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_580_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_581_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_745_not_fold5_train_${dataset.missing_rate}.json
  - /sda2/datasets/MiceBone/splits_missing/Id_966_not_fold5_train_${dataset.missing_rate}.json
  train_complete_files:
  - /sda2/datasets/MiceBone/split_folds/Id_290_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_47_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_533_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_534_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_580_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_581_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_745_not_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_966_not_fold5.json
  train_ground_truth_file: /sda2/datasets/MiceBone/split_folds/majority_vote_not_fold5.json
  test_files:
  - /sda2/datasets/MiceBone/split_folds/Id_290_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_47_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_533_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_534_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_580_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_581_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_745_fold5.json
  - /sda2/datasets/MiceBone/split_folds/Id_966_fold5.json
  test_ground_truth_file: /sda2/datasets/MiceBone/split_folds/majority_vote_fold5.json

data_augmentation:
  resize: null
  padding_px: null
  crop_size: null
  prob_random_flip: 0.5
  mean: null
  std: null

model:
  _partial_: True
  _target_: models.ResNet.resnet18
  in_channels: 3  # color images: 3, black and white: 1
  conv1_kernel_size: [7, 7]

training:
  gating_lr: 0.01
  expert_lr: 0.01
  batch_size: 128
  num_epochs: 300
  clipped_norm: null

hparams:
  epsilon_lower: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  epsilon_upper: [1., 1., 1., 1., 1., 1., 1., 1., 0.2]